config/routes.rb
Rails.application.routes.draw do
  resources :comments
devise_for :users, :controllers => { :registrations => "registrations" }
  resources :posts
  resources :users 
  resources :comments

  root "posts#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

#                   Prefix Verb   URI Pattern                    Controller#Action
#         new_user_session GET    /users/sign_in(.:format)       devise/sessions#new
#             user_session POST   /users/sign_in(.:format)       devise/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)      devise/sessions#destroy
#        new_user_password GET    /users/password/new(.:format)  devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format) devise/passwords#edit
#            user_password PATCH  /users/password(.:format)      devise/passwords#update
#                          PUT    /users/password(.:format)      devise/passwords#update
#                          POST   /users/password(.:format)      devise/passwords#create
# cancel_user_registration GET    /users/cancel(.:format)        devise/registrations#cancel
#    new_user_registration GET    /users/sign_up(.:format)       devise/registrations#new
#   edit_user_registration GET    /users/edit(.:format)          devise/registrations#edit
#        user_registration PATCH  /users(.:format)               devise/registrations#update
#                          PUT    /users(.:format)               devise/registrations#update
#                          DELETE /users(.:format)               devise/registrations#destroy
#                          POST   /users(.:format)               devise/registrations#create
#                    posts GET    /posts(.:format)               posts#index
#                          POST   /posts(.:format)               posts#create
#                 new_post GET    /posts/new(.:format)           posts#new
#                edit_post GET    /posts/:id/edit(.:format)      posts#edit
#                     post GET    /posts/:id(.:format)           posts#show
#                          PATCH  /posts/:id(.:format)           posts#update
#                          PUT    /posts/:id(.:format)           posts#update
#                          DELETE /posts/:id(.:format)           posts#destroy
#                     root GET    /                              posts#index

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  # attr_accessor :body, :commenter, :post
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
  belongs_to :user

#   has_many :comments, :dependent => :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
# before_action :require_permission, only: [:new]

      def index
  @comment = Comment.all
end


    def new
      @comment = Comment.new
    end

    def create
      

        #     @post = Post.find(params[:comment][:post_id])
        # # @comment = @post.comments.create(params[:comment])
        # #     redirect_to post_path(@post)

      @comment = Comment.new(commentParams)
       @comment.user_id = current_user[:id]
      if @comment.save
        
        flash[:success] = "Comment successfully added"
        redirect_to post_path(@comment.post_id)
      else
        render 'new'
      end
    end

    #   def create
    #     @post = Post.find(params[:post_id])
    #     @comment = @post.comments.create(params[:comment])
    #     redirect_to post_path(@post)
    #   end

    def destroy
       @post = Comment.find(params[:id])
       @comment = Comment.find(params[:id])
       @comment.destroy
       redirect_to post_path(@post[:post_id])
      end

      private

      def commentParams
        params.require(:comment).permit(:body, :post_id)
      end


#  private
#     # Use callbacks to share common setup or constraints between actions.
    
    
#     def require_permission
#     if user_signed_in == false
#         redirect_to root_path
#         #Or do something else here
#       end
#     end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
before_action :require_permission, only: [:edit, :update, :destroy]




  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = current_user.posts.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end
    
    def require_permission
      if current_user != Post.find(params[:id]).user
        redirect_to root_path
        #Or do something else here
      end
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController





  def create
    build_resource(registration_params)
 
    if resource.save
      if resource.active_for_authentication?
        set_flash_message :notice, :signed_up if is_navigational_format?
        sign_up(resource_name, resource)
        respond_with resource, :location => after_sign_up_path_for(resource)
      else
        set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_navigational_format?
        respond_with resource, :location => after_sign_up_path_for(resource)
      end
    else
      clean_up_passwords
      respond_with resource
    end
  end  
 
  private

  def registration_params
    params.require(:user).permit(:email, :name, :picture, :about, :password, :password_confirmation)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @posts = @user.posts
  end

  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<article class="row">
  <div class="col-md-2 col-sm-2 hidden-xs">
  <%= link_to User.find(comment.user_id) do %>

    <figure class="thumbnail">
      <img class="img-responsive" src=<%= User.find(comment.user_id).picture %> />
      <figcaption class="text-center"><%= User.find(comment.user_id).name %></figcaption>
    </figure>
    <% end %>
  </div>
  <div class="col-md-10 col-sm-10">
    <div class="panel panel-default arrow left">
      <div class="panel-body">
        <header class="text-left">
          <div class="comment-user"><i class="fa fa-user"></i> <%= link_to User.find(comment.user_id).name, User.find(comment.user_id) %></div>
          <time class="comment-date" datetime="16-12-2014 01:05"><i class="fa fa-clock-o"></i> <%= comment.created_at %></time>
        </header>
        <div class="comment-post">
          <p>
           <%=simple_format h comment.body %>
          </p>
        </div>
   
        <% if user_signed_in? %>
          <% if current_user.id == User.find(comment.user_id).id %>
          <p class="text-right">
          <span class="commentDeleteBttn">
          <i class="fa fa-trash"></i> <%= link_to 'Delete', [(comment)], method: :delete, data: { confirm: 'Are you sure?' } %>
          </span>
          </p>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</article>

app/views/comments/_form.html.erb
<%= form_for([@post_path, @post.comments.build]) do |f| %>
  <div class="addCommentContainer" style="margin-top: -18px;>
    <div class="field">
      <%= f.label :body %><br />
      <%= f.text_area :body %>
    </div>
    <div class="actions">
      <%= f.submit class: 'btn-primary' %>
    </div>
      <%= f.hidden_field :post_id %>
  </div>
<% end %> 

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'shared/errors', obj: @comment %>

<div class="row">
<div class="col-xs-12">
  <%= form_for(@comment, :html => {class: "form-horizontal", role: "form"}) do |f| %>

  <div class="form-group">
    <div class="control-label col-sm-2">
      <%= f.label :comment %>
    </div>

    <div class="col-sm-8">
      <%= f.text_area :comment, rows: 3, class: "form-control", placeholder: "Please enter a comment", autofocus: true %>
    </div>
  </div>

  <div class="form-group">
    <div class="center col-sm-offset-1 col-sm-10">
    
      <%= f.submit class: "btn btn-primary btn-lg" %>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
<title>Article Website</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <%= stylesheet_link_tag "main" %>
</head>

<body>
<div id="wrapper">
  <div id="header">
    <nav class="navbar navbar bg-primary" role="navigation">
      <div class="leftSide">
        <%= link_to('/') do %>
          <li>
            Home
          </li>
        <% end %>
        <%= link_to(new_post_path) do %>
          <li>
            New Article
          </li>
        <% end %>
        <%= link_to(users_path) do %>
          <li>
            All Users
          </li>
        <% end %>
      </div>

      <div class="rightSide">
      <% if user_signed_in? %>
        <div class="dropdown">
          <button class="btn btn-default " type="button" id="menu1" data-toggle="dropdown"><img class="navbarProfilePicture" src='https://ssl.gstatic.com/accounts/ui/avatar_2x.png' /></button>
          <ul class="dropdown-menu" role="menu" aria-labelledby="menu1">
            <li role="presentation">
              <a href="/users/<%= current_user.id %>" role="menuitem" tabindex="-1">
                My Profile
              </a>
            </li>
            <li role="presentation">
              <a href="<%= edit_user_registration_path %>" role="menuitem" tabindex="-1">
                Edit Profile 
              </a>
            </li>
          </ul>
        </div>
        <%= link_to destroy_user_session_path, :method => :delete do %>
          <li>
            Log Out
          </li>
        <% end %>

        <% else %>
        <%= link_to new_user_session_path do %>
          <li>
            Log In
          </li>
        <% end %>
        <%= link_to new_user_registration_path do %>
          <li>
            Register
          </li>
        <% end %>
      <% end %>
      </div>
    </nav>
  </div>

  <div id="content">
    <%= yield %>
  </div>
  
  <div id="footer">
    <footer>Copyright 2017 -- <a href="https://github.com/askflow1111">Made By Muhammad Usman</a></footer>
  </div>
</div>
</body>

</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="editPostFormContainer">
    <div class="field">
      <%= form.label :title %>
      <div class="title">
      <%= form.text_field :title, id: :post_title %>
      </div>
    </div>

    <div class="field content">
      <%= form.label :content %>
      <%= form.text_area :content, id: :post_content %>
    </div>

    <div class="actions Bttn">
      <%= form.submit %>
    </div>
    
    <%= link_to( @post) do %>
      <div class="actions">
    <input type="submit" name="cancel" value="Cancel Post">
      </div>
    <% end %>
  </div>

<% end %>

app/views/posts/edit.html.erb
<h2 class="pageTitleEditPost">Editing Article</h2>

<%= render 'form', post: @post %>

app/views/posts/index.html.erb
<p id="notice" class="alert alert-success"><%= notice %></p>

<div class="mainPagePostContainer">
  <% @posts.each do |post| %>
    <div class="eachPost">
        <div class="title"><%= post.title %></div>
            <div class="info">

        <i class="fa fa-user"></i> 
        <div class="userName"><%= link_to post.user.name, post.user %></div>
        <div class="postDate">
          <i class="fa fa-clock-o"></i>
          <%= post.created_at %>
        </div>
      </div>
      <div class="content shortContent"><%=  post.content %></div>
      
      <div class="readMore"><%= link_to 'Read More -->>', post %></div> 
      <div class="last-line">....</div>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<h2 class="pageTitleNewPost">New Article</h2>

<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<p id="notice" class="alert alert-success"><%= notice %></p>

<div class="postContainer">
<div class="postRightBttnContainer">
<% if user_signed_in? %>
  <% if current_user.id == Post.find(params[:id]).user_id %>
  <div class="editAndDeleteBttnContainer">
    <div class="editPostBttn">
      <%= link_to 'Edit', edit_post_path(@post) %>
    </div>
    <div class="deletePostBttn">
      <%= link_to 'Delete', @post, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
  </div>
  <% end %>
<% end %>
</div>


  <div class="postTitle">
    <%= @post.title %>
  </div>

  <div class="postAuthor">
    <i class="fa fa-user"></i> 
    <%= link_to @post.user.name, @post.user %>  
  </div>

  <div class="postDate">
    <i class="fa fa-clock-o"></i>
    <%= @post.created_at %>
  </div>

  <div class="postContent">
    <%=simple_format h @post.content %>
  </div>

</div>




  


<div class="postCommentsContainer">
  <div class="postReadCommentsContainer">
    <div class="container">
      <div class="row">
        <div class="col-md-8">
          <h2 class="page-header">Comments</h2>
          <section class="comment-list">
        <%= render @post.comments %>
          </section>
        </div>
      </div>
    </div>
  </div>
  
  <div class="postAddCommentContainer">
  <div class="addCommentWidth">
    <h2 class='page-header'>Add a comment:</h2>
    <%= render "comments/form" %>
    </div>
  </div>

 
 </div>

app/views/users/index.html.erb
<div class="showAllUsers">

<% @users.each do |user| %>
  <div class="eachUserContainer">
    <%= link_to(user) do %>
      <div class="eachUser">

        <div class="userPicture">
          <img src=<%= user.picture %> alt="Profile Picture">
        </div>

        <div class="userName">
          <%= user.name %>
        </div>

      </div>
      <% end %>
    </div>
<% end %>

</div>

app/views/users/show.html.erb
<div class="user-profile">
<h1>
<div class="name"> 
Name: <%= @user.name %>
</div> 
<div class="email"> 
Email: <%= @user.email %>
</div> 
<div class="email"> 
About: <%= @user.about %>
</div>  
<div> 
<img src=<%= @user.picture %> alt="Profile Picture" height="180" width="180">
</div> 
<br>
  <div>

 <%   if @posts.length != 0 %>
  
    <% @posts.each do |post| %>
      <div class="each-post">
        <div class="title">
          <%= post.title %>
        </div>
        <div class="content">
          <%= post.content %>
        </div>
      </div>
    <br>
       <% end %>
     <% else %>
    <h3 class="no-article-message">
    Sorry the user doesn't have any articles.
     </h3>
  <% end %>
  </div>



</h1>
</div>